### PR TITLE
Make the SQLStatementCountMismatchException extend an AssertionError

### LINKED ISSUE #4: SQLStatementCountMismatchException is interpreted as a test error instead of a test failure by some test runners
Hi,

the ```SQLStatementCountMismatchException``` is interpreted as a test error instead of a test failure by some test runners.

With following sample test class:
``` java

import com.vladmihalcea.sql.SQLStatementCountValidator;
import org.junit.Test;

import static org.junit.Assert.*;

public class SampleTest {

  @Test
  public void testThatAlwaysFails() {
    assertTrue(false);
  }

  @Test
  public void testWithError() {
    throw new RuntimeException();
  }

  @Test
  public void sqlCountTest() {
    SQLStatementCountValidator.assertSelectCount(10);
  }
}
```
IDEA displays ```sqlCountTest()``` test as having an error from the tested source code instead of a test failure (e.g. ```testThatAlwaysFails()```) 
nov15_221127

This is also applied when running tests with Maven:
``` 
$ mvn test
```
```
...
Results :

Failed tests:   testThatAlwaysFails(SampleTest)

Tests in error: 
  sqlCountTest(SampleTest): Expected 10 statements but recorded 0 instead!
  testWithError(SampleTest)

Tests run: 3, Failures: 1, Errors: 2, Skipped: 0
```

This happens because [SQLStatementCountMismatchException](https://github.com/vladmihalcea/db-util/blob/master/src/main/java/com/vladmihalcea/sql/exception/SQLStatementCountMismatchException.java) extends ``` RuntimeException ``` instead of ``` AssertionError ```.

If the ```SQLStatementCountMismatchException``` will extend the ```AssertionError``` I think it should be renamed to ```SQLStatementCountMismatchAssertionError``` and its subclasses also should contain ```AssertionError``` instead of ```Exception``` in their names.

I'd like to submit a PR if you don't mind the proposed changes

### PR DESCRIPTION
**Pull request by cac03**
Fixes #4

### CODE REVIEW

File: src/main/java/com/vladmihalcea/sql/exception/SQLDeleteCountMismatchAssertionError.java [hunk 1]
```diff
@@ -6,9 +6,9 @@
  *
  * @author Vlad Mihalcea
  */
-public class SQLDeleteCountMismatchException extends SQLStatementCountMismatchException {
+public class SQLDeleteCountMismatchAssertionError extends SQLStatementCountMismatchAssertionError {
```
Comment (vladmihalcea) [inline src/main/java/com/vladmihalcea/sql/exception/SQLDeleteCountMismatchAssertionError.java]: Renaming the Exception will break backward compatibility. I'm not sure if it's worth.

Anyway, calling it an `Error` is even worse. For instance, Mockito or JUnit drop the `Error` part when extending `AssertionError`.

File: src/main/java/com/vladmihalcea/sql/exception/SQLStatementCountMismatchAssertionError.java [hunk 2]
```diff
@@ -6,12 +6,12 @@
  *
  * @author Vlad Mihalcea
  */
-public abstract class SQLStatementCountMismatchException extends RuntimeException {
+public abstract class SQLStatementCountMismatchAssertionError extends AssertionError {
```
Comment (vladmihalcea) [inline src/main/java/com/vladmihalcea/sql/exception/SQLStatementCountMismatchAssertionError.java]: Why not just change the `SQLStatementCountMismatchException` extend `AssertionError` instead?

**Comment by cac03** [comment]
Did as you suggested.
Now ```SQLStatementCountMismatchException``` simply extends an ```AssertionError```
